version: '3.1'
services :
  warehouse:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    restart: always
  oltp:
    image: postgres:13-alpine
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: production
      POSTGRES_PASSWORD: production
      POSTGRES_DB: production
    restart: always
  admin:
    image: adminer
    restart: always
    depends_on: 
      - warehouse_db
      - oltp_db
    ports:
      - 8080:8080