version: '3.6'
services :
  ecommerce:
    image: "mariadb:10.4"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Sofia
    
  warehouse:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    restart: always
  admin:
    image: adminer
    restart: always
    depends_on: 
      - warehouse
      - ecommerce
    ports:
      - 8080:8080
  airflowdb:
    image: postgres:13-alpine
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
  scheduler:
      image: apache/airflow
      command: scheduler
      container_name: airflow
      depends_on:
          - airflowdb
          - airflowweb
      env_file:
          - .env
      volumes:
          - ./airflow/dags:/opt/airflow/dags
          - ./airflow/logs:/opt/airflow/logs
          - ./airflow/plugins:/opt/airflow/plugins
  airflowweb:
      image: apache/airflow
      entrypoint: ./scripts/entrypoint.sh
      container_name: airflowweb
      env_file:
          - .env
      volumes:
          - ./airflow/dags:/opt/airflow/dags
          - ./airflow/logs:/opt/airflow/logs
          - ./airflow/scripts:/opt/airflow/scripts
          - ./airflow/plugins:/opt/airflow/plugins
      ports:
          - 8181:8080
